version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: 'eventdb'
      POSTGRES_USER: 'apuha'
      POSTGRES_PASSWORD: '12345678'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d eventdb -U apuha" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
    - ./scripts:/docker-entrypoint-initdb.d
    - psql-data:/var/lib/postgresql/
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
  psql-data: